name: pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia o código do repositório
        uses: actions/checkout@v4
      
      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instalar dependências com Poetry
        run: |
          pip install poetry
          poetry install
