name: pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4
      
      - name: Configura o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instala dependências
        run: |
          pip install poetry
          poetry install
          
      - name: Roda os testes
        run: poetry run pytest
