name: pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia o código
        uses: actions/checkout@v4
      
      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      
      - name: Instalar as dependências
        run: pip install -r requirements.txt
      
     